---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: <идентификатор_ключа_доступа>
  secretAccessKey: <секретный_ключ>
  endpoint: https://storage.yandexcloud.net
