apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homework
  name: websrv-ingresss
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    ingressClassName: nginx
    rules:
    - host: homework.otus
      http:
        paths:
        - pathType: Prefix
          path: /homework
          backend:
            service:
              name: websrv-service
              port:
                number: 80