{{- if .Values.serviceAccount.create -}}
{{- $fullName := include "websrv.serviceAccountName" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "websrv.serviceAccountName" . -}}
subjects:
  - kind: ServiceAccount
    name: {{ include "websrv.serviceAccountName" . }}
    namespace: {{.Values.namespace}}
{{- end }}