{{- if .Values.serviceAccount.create -}}
{{- $fullName := include "websrv.serviceAccountName" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}-cr
rules:
    - nonResourceURLs:
          {{- .Values.clusterRole.nonResourceURLs}}
      {{- with .Values.clusterRole.verbs }}
      verbs:
      {{- toYaml . | nindent 4 }}
      {{- end }}
{{- end }}
