{{- if .Values.persistence.enabled -}}
{{- $fullName := include "websrv.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-pvc
  namespace: {{.Values.namespace}}
  labels:
    {{- include "websrv.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ $fullName }}-sc
{{- else }}
    storageClassName: standard
{{- end }}
{{- end }}