apiVersion: v1
kind: Service
metadata:
  name: {{ include "websrv.fullname" . }}-service
  namespace: {{.Values.namespace}}
  labels:
    {{- include "websrv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: websrv-port
      protocol: TCP
      name: http
  selector:
    {{- include "websrv.selectorLabels" . | nindent 4 }}
