apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL: "https://github.com/Kuber-2024-02OTUS/boch333_repo.git"
    path: "kubernetes-networks"
    targetRevision: "kubernetes-gitops"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true