apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-servicemonitor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      port: metrics
      interval: 15s