apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://192.168.49.2:8443
  name: minikube
users:
- name: cd
  user:
    as-user-extra: {}
    token:  $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    client-key: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
contexts:
- context:
    cluster: minikube
    namespace: homework
    user: cd
  name: homework
current-context: homework
