kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-admin-binding
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: ""