apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-monitoring
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: role-monitoring
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: monitoring