apiVersion: v1
kind: Secret
metadata:
  name: cd-user-secret
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
automountServiceAccountToken: true
secrets:
  - name: cd-user-secret