apiVersion: v2
name: monitoring
description: A Helm chart monitoring for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus
    version: 9.0.5
    repository: https://charts.bitnami.com/bitnami
    alias: prometheus-operator
    condition: prometheus-operator.enabled
