apiVersion: v2
name: websrv
description: A Helm chart for Kubernetes

type: application
version: 0.1.1
appVersion: "1.16.1"

dependencies:
- name: redis
  version: 19.0.1
  repository: https://charts.bitnami.com/bitnami
