# Default values for websrv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

resources:
    limits:
      cpu: "100m"
      memory: "40Mi"
    requests:
      cpu: ""
      memory: ""

probe:
  enabled: true

image:
  repository: nginroflmaoinmysoul/otusx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: "homework"

configMap:
  enabled: true
  data:  {
    log_level: INFO,
    kubeapi:  https://192.168.49.2:8443,
    sa: /var/run/secrets/kubernetes.io/serviceaccount
  }

storageClass:
  enabled: true
  provisioner: k8s.io/minikube-hostpath
  reclaimPolicy: Retain
  volumeBindingMode: Immediate

persistence:
  enabled: true
  storageClass: "-"
  accessMode: ReadWriteOnce
  size: 2Mi


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "monitoring"

ClusterRole:

  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "monitoring"
  nonResourceURLs: "/metrics"
  verbs: get

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {
        nginx.ingress.kubernetes.io/use-regex: "true",
        nginx.ingress.kubernetes.io/rewrite-target: /$1
  }
  hosts:
    - host: "homework.otus"
      paths:
        - path: "/conf/metric"
          pathType: Prefix
    
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
