kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-operator
subjects:
- kind: ServiceAccount
  name: operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: full-access-api
  apiGroup: rbac.authorization.k8s.io