apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-operator
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      serviceAccountName: operator
      containers:
      - name: mysql-operator-container
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"