apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websrv-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Mi